public class App {
    public static void main(String[] args) throws Exception {
        int x = 10;
        int y = 20;
        int z = 5;
        System.out.println(y);

        try {
            
        } catch (Exception e) {
            System.out.println("Error de division");
        }

        // throw Llama a un bloque catch
    }
}
